"""swaggerpetstoreopenapi30.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from swaggerpetstoreopenapi30.api_helper import (
    APIHelper,
)
from swaggerpetstoreopenapi30.utilities.xml_utilities import (
    XmlUtilities,
)


class ApiResponse(object):
    """Implementation of the 'ApiResponse' model.

    Attributes:
        code (int): The model property of type int.
        mtype (str): The model property of type str.
        message (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": "code",
        "mtype": "type",
        "message": "message",
    }

    _optionals = [
        "code",
        "mtype",
        "message",
    ]

    def __init__(
        self,
        code=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        message=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a ApiResponse instance."""
        # Initialize members of the class
        if code is not APIHelper.SKIP:
            self.code = code
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if message is not APIHelper.SKIP:
            self.message = message

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(code,
                   mtype,
                   message,
                   additional_properties)

    @classmethod
    def from_element(cls, root):
        """Initialize an instance of this class using an xml.etree.Element.

        Args:
            root (string): The root xml element.

        Returns:
            object: An instance of this class.

        """
        code = XmlUtilities.value_from_xml_element(root.find("code"), int)
        mtype = XmlUtilities.value_from_xml_element(root.find("type"), str)
        message = XmlUtilities.value_from_xml_element(root.find("message"), str)

        return cls(code,
                   mtype,
                   message,
                   additional_properties)

    def to_xml_sub_element(self, root):
        """Convert this object to an instance of xml.etree.Element.

        Args:
            root (xml.etree.Element): The parent of this xml element.

        """
        XmlUtilities.add_as_subelement(root, self.code, "code")
        XmlUtilities.add_as_subelement(root, self.mtype, "type")
        XmlUtilities.add_as_subelement(root, self.message, "message")

    def __repr__(self):
        """Return a unambiguous string representation."""
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"code={_code!r}, "
            f"mtype={_mtype!r}, "
            f"message={_message!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"code={_code!s}, "
            f"mtype={_mtype!s}, "
            f"message={_message!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
