"""swaggerpetstoreopenapi30.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from swaggerpetstoreopenapi30.api_helper import (
    APIHelper,
)
from swaggerpetstoreopenapi30.utilities.xml_utilities import (
    XmlUtilities,
)


class Order(object):
    """Implementation of the 'Order' model.

    Attributes:
        id (int): The model property of type int.
        pet_id (int): The model property of type int.
        quantity (int): The model property of type int.
        ship_date (datetime): The model property of type datetime.
        status (OrderStatus): Order Status
        complete (bool): The model property of type bool.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "pet_id": "petId",
        "quantity": "quantity",
        "ship_date": "shipDate",
        "status": "status",
        "complete": "complete",
    }

    _optionals = [
        "id",
        "pet_id",
        "quantity",
        "ship_date",
        "status",
        "complete",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        pet_id=APIHelper.SKIP,
        quantity=APIHelper.SKIP,
        ship_date=APIHelper.SKIP,
        status=APIHelper.SKIP,
        complete=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Order instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if pet_id is not APIHelper.SKIP:
            self.pet_id = pet_id
        if quantity is not APIHelper.SKIP:
            self.quantity = quantity
        if ship_date is not APIHelper.SKIP:
            self.ship_date =\
                 APIHelper.apply_datetime_converter(
                ship_date, APIHelper.RFC3339DateTime)\
                 if ship_date else None
        if status is not APIHelper.SKIP:
            self.status = status
        if complete is not APIHelper.SKIP:
            self.complete = complete

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        pet_id =\
            dictionary.get("petId")\
            if dictionary.get("petId")\
                else APIHelper.SKIP
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity")\
                else APIHelper.SKIP
        ship_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("shipDate")).datetime\
            if dictionary.get("shipDate") else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        complete =\
            dictionary.get("complete")\
            if "complete" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   pet_id,
                   quantity,
                   ship_date,
                   status,
                   complete,
                   additional_properties)

    @classmethod
    def from_element(cls, root):
        """Initialize an instance of this class using an xml.etree.Element.

        Args:
            root (string): The root xml element.

        Returns:
            object: An instance of this class.

        """
        id = XmlUtilities.value_from_xml_element(root.find("id"), int)
        pet_id = XmlUtilities.value_from_xml_element(root.find("petId"), int)
        quantity = XmlUtilities.value_from_xml_element(root.find("quantity"), int)
        ship_date = XmlUtilities.value_from_xml_element(root.find("shipDate"), APIHelper.RFC3339DateTime)
        status = XmlUtilities.value_from_xml_element(root.find("status"), str)
        complete = XmlUtilities.value_from_xml_element(root.find("complete"), bool)

        return cls(id,
                   pet_id,
                   quantity,
                   ship_date,
                   status,
                   complete,
                   additional_properties)

    def to_xml_sub_element(self, root):
        """Convert this object to an instance of xml.etree.Element.

        Args:
            root (xml.etree.Element): The parent of this xml element.

        """
        XmlUtilities.add_as_subelement(root, self.id, "id")
        XmlUtilities.add_as_subelement(root, self.pet_id, "petId")
        XmlUtilities.add_as_subelement(root, self.quantity, "quantity")
        XmlUtilities.add_as_subelement(root, self.ship_date, "shipDate")
        XmlUtilities.add_as_subelement(root, self.status, "status")
        XmlUtilities.add_as_subelement(root, self.complete, "complete")

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _pet_id=(
            self.pet_id
            if hasattr(self, "pet_id")
            else None
        )
        _quantity=(
            self.quantity
            if hasattr(self, "quantity")
            else None
        )
        _ship_date=(
            self.ship_date
            if hasattr(self, "ship_date")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _complete=(
            self.complete
            if hasattr(self, "complete")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"pet_id={_pet_id!r}, "
            f"quantity={_quantity!r}, "
            f"ship_date={_ship_date!r}, "
            f"status={_status!r}, "
            f"complete={_complete!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _pet_id=(
            self.pet_id
            if hasattr(self, "pet_id")
            else None
        )
        _quantity=(
            self.quantity
            if hasattr(self, "quantity")
            else None
        )
        _ship_date=(
            self.ship_date
            if hasattr(self, "ship_date")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _complete=(
            self.complete
            if hasattr(self, "complete")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"pet_id={_pet_id!s}, "
            f"quantity={_quantity!s}, "
            f"ship_date={_ship_date!s}, "
            f"status={_status!s}, "
            f"complete={_complete!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
