"""swaggerpetstoreopenapi30.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from swaggerpetstoreopenapi30.api_helper import (
    APIHelper,
)
from swaggerpetstoreopenapi30.models.category import (
    Category,
)
from swaggerpetstoreopenapi30.models.tag import (
    Tag,
)
from swaggerpetstoreopenapi30.utilities.xml_utilities import (
    XmlUtilities,
)


class Pet(object):
    """Implementation of the 'Pet' model.

    Attributes:
        id (int): The model property of type int.
        name (str): The model property of type str.
        category (Category): The model property of type Category.
        photo_urls (List[str]): The model property of type List[str].
        tags (List[Tag]): The model property of type List[Tag].
        status (PetStatus): pet status in the store
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "photo_urls": "photoUrls",
        "id": "id",
        "category": "category",
        "tags": "tags",
        "status": "status",
    }

    _optionals = [
        "id",
        "category",
        "tags",
        "status",
    ]

    def __init__(
        self,
        name=None,
        photo_urls=None,
        id=APIHelper.SKIP,
        category=APIHelper.SKIP,
        tags=APIHelper.SKIP,
        status=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Pet instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        self.name = name
        if category is not APIHelper.SKIP:
            self.category = category
        self.photo_urls = photo_urls
        if tags is not APIHelper.SKIP:
            self.tags = tags
        if status is not APIHelper.SKIP:
            self.status = status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else None
        photo_urls =\
            dictionary.get("photoUrls")\
            if dictionary.get("photoUrls")\
                else None
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        category =\
            Category.from_dictionary(
                dictionary.get("category"))\
                if "category" in dictionary.keys()\
                else APIHelper.SKIP
        tags = None
        if dictionary.get("tags") is not None:
            tags = [
                Tag.from_dictionary(x)
                    for x in dictionary.get("tags")
            ]
        else:
            tags = APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(name,
                   photo_urls,
                   id,
                   category,
                   tags,
                   status,
                   additional_properties)

    @classmethod
    def from_element(cls, root):
        """Initialize an instance of this class using an xml.etree.Element.

        Args:
            root (string): The root xml element.

        Returns:
            object: An instance of this class.

        """
        name = XmlUtilities.value_from_xml_element(root.find("name"), str)
        photo_urls = XmlUtilities.list_from_xml_element(
            root, "photoUrl", str, wrapping_element_name="photoUrls")
        id = XmlUtilities.value_from_xml_element(root.find("id"), int)
        category = XmlUtilities.value_from_xml_element(root.find("category"), Category)
        tags = XmlUtilities.list_from_xml_element(
            root, "tag", Tag, wrapping_element_name="tags")
        status = XmlUtilities.value_from_xml_element(root.find("status"), str)

        return cls(name,
                   photo_urls,
                   id,
                   category,
                   tags,
                   status,
                   additional_properties)

    def to_xml_sub_element(self, root):
        """Convert this object to an instance of xml.etree.Element.

        Args:
            root (xml.etree.Element): The parent of this xml element.

        """
        XmlUtilities.add_as_subelement(root, self.name, "name")
        XmlUtilities.add_list_as_subelement(root, self.photo_urls, "photoUrl",
                                            wrapping_element_name="photoUrls")
        XmlUtilities.add_as_subelement(root, self.id, "id")
        XmlUtilities.add_as_subelement(root, self.category, "category")
        XmlUtilities.add_list_as_subelement(root, self.tags, "tag",
                                            wrapping_element_name="tags")
        XmlUtilities.add_as_subelement(root, self.status, "status")

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=self.name
        _category=(
            self.category
            if hasattr(self, "category")
            else None
        )
        _photo_urls=self.photo_urls
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"category={_category!r}, "
            f"photo_urls={_photo_urls!r}, "
            f"tags={_tags!r}, "
            f"status={_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=self.name
        _category=(
            self.category
            if hasattr(self, "category")
            else None
        )
        _photo_urls=self.photo_urls
        _tags=(
            self.tags
            if hasattr(self, "tags")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"category={_category!s}, "
            f"photo_urls={_photo_urls!s}, "
            f"tags={_tags!s}, "
            f"status={_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
