"""swaggerpetstoreopenapi30.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from swaggerpetstoreopenapi30.api_helper import (
    APIHelper,
)
from swaggerpetstoreopenapi30.utilities.xml_utilities import (
    XmlUtilities,
)


class User(object):
    """Implementation of the 'User' model.

    Attributes:
        id (int): The model property of type int.
        username (str): The model property of type str.
        first_name (str): The model property of type str.
        last_name (str): The model property of type str.
        email (str): The model property of type str.
        password (str): The model property of type str.
        phone (str): The model property of type str.
        user_status (int): User Status
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "username": "username",
        "first_name": "firstName",
        "last_name": "lastName",
        "email": "email",
        "password": "password",
        "phone": "phone",
        "user_status": "userStatus",
    }

    _optionals = [
        "id",
        "username",
        "first_name",
        "last_name",
        "email",
        "password",
        "phone",
        "user_status",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        username=APIHelper.SKIP,
        first_name=APIHelper.SKIP,
        last_name=APIHelper.SKIP,
        email=APIHelper.SKIP,
        password=APIHelper.SKIP,
        phone=APIHelper.SKIP,
        user_status=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a User instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if username is not APIHelper.SKIP:
            self.username = username
        if first_name is not APIHelper.SKIP:
            self.first_name = first_name
        if last_name is not APIHelper.SKIP:
            self.last_name = last_name
        if email is not APIHelper.SKIP:
            self.email = email
        if password is not APIHelper.SKIP:
            self.password = password
        if phone is not APIHelper.SKIP:
            self.phone = phone
        if user_status is not APIHelper.SKIP:
            self.user_status = user_status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        username =\
            dictionary.get("username")\
            if dictionary.get("username")\
                else APIHelper.SKIP
        first_name =\
            dictionary.get("firstName")\
            if dictionary.get("firstName")\
                else APIHelper.SKIP
        last_name =\
            dictionary.get("lastName")\
            if dictionary.get("lastName")\
                else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email")\
                else APIHelper.SKIP
        password =\
            dictionary.get("password")\
            if dictionary.get("password")\
                else APIHelper.SKIP
        phone =\
            dictionary.get("phone")\
            if dictionary.get("phone")\
                else APIHelper.SKIP
        user_status =\
            dictionary.get("userStatus")\
            if dictionary.get("userStatus")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   username,
                   first_name,
                   last_name,
                   email,
                   password,
                   phone,
                   user_status,
                   additional_properties)

    @classmethod
    def from_element(cls, root):
        """Initialize an instance of this class using an xml.etree.Element.

        Args:
            root (string): The root xml element.

        Returns:
            object: An instance of this class.

        """
        id = XmlUtilities.value_from_xml_element(root.find("id"), int)
        username = XmlUtilities.value_from_xml_element(root.find("username"), str)
        first_name = XmlUtilities.value_from_xml_element(root.find("firstName"), str)
        last_name = XmlUtilities.value_from_xml_element(root.find("lastName"), str)
        email = XmlUtilities.value_from_xml_element(root.find("email"), str)
        password = XmlUtilities.value_from_xml_element(root.find("password"), str)
        phone = XmlUtilities.value_from_xml_element(root.find("phone"), str)
        user_status = XmlUtilities.value_from_xml_element(root.find("userStatus"), int)

        return cls(id,
                   username,
                   first_name,
                   last_name,
                   email,
                   password,
                   phone,
                   user_status,
                   additional_properties)

    def to_xml_sub_element(self, root):
        """Convert this object to an instance of xml.etree.Element.

        Args:
            root (xml.etree.Element): The parent of this xml element.

        """
        XmlUtilities.add_as_subelement(root, self.id, "id")
        XmlUtilities.add_as_subelement(root, self.username, "username")
        XmlUtilities.add_as_subelement(root, self.first_name, "firstName")
        XmlUtilities.add_as_subelement(root, self.last_name, "lastName")
        XmlUtilities.add_as_subelement(root, self.email, "email")
        XmlUtilities.add_as_subelement(root, self.password, "password")
        XmlUtilities.add_as_subelement(root, self.phone, "phone")
        XmlUtilities.add_as_subelement(root, self.user_status, "userStatus")

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _password=(
            self.password
            if hasattr(self, "password")
            else None
        )
        _phone=(
            self.phone
            if hasattr(self, "phone")
            else None
        )
        _user_status=(
            self.user_status
            if hasattr(self, "user_status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"username={_username!r}, "
            f"first_name={_first_name!r}, "
            f"last_name={_last_name!r}, "
            f"email={_email!r}, "
            f"password={_password!r}, "
            f"phone={_phone!r}, "
            f"user_status={_user_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _username=(
            self.username
            if hasattr(self, "username")
            else None
        )
        _first_name=(
            self.first_name
            if hasattr(self, "first_name")
            else None
        )
        _last_name=(
            self.last_name
            if hasattr(self, "last_name")
            else None
        )
        _email=(
            self.email
            if hasattr(self, "email")
            else None
        )
        _password=(
            self.password
            if hasattr(self, "password")
            else None
        )
        _phone=(
            self.phone
            if hasattr(self, "phone")
            else None
        )
        _user_status=(
            self.user_status
            if hasattr(self, "user_status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"username={_username!s}, "
            f"first_name={_first_name!s}, "
            f"last_name={_last_name!s}, "
            f"email={_email!s}, "
            f"password={_password!s}, "
            f"phone={_phone!s}, "
            f"user_status={_user_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
