# -*- coding: utf-8 -*-

"""
cypresstestapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from cypresstestapi.api_helper import APIHelper
from cypresstestapi.models.tokens_request import TokensRequest
from cypresstestapi.models.multiple_arrays_request import MultipleArraysRequest


class APIControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(APIControllerTests, cls).setUpClass()
        cls.controller = cls.client.client
        cls.response_catcher = cls.controller.http_call_back

    # Generates a new OAuth token with the specified scopes.
    def test_create_o_auth_token(self):
        # Parameters for the API call
        body = None

        # Perform the API call through the SDK function
        self.controller.create_o_auth_token(body)

        # Test response code
        assert self.response_catcher.response.status_code == 201

    # This endpoint accepts a complex structure with multiple arrays.
    def test_test_endpointwith_arrays(self):
        # Parameters for the API call
        body = None

        # Perform the API call through the SDK function
        self.controller.test_endpointwith_arrays(body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

