
"""
cypresstestapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291, W293, E501
from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class APIControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.client
        cls.response_catcher = cls.controller.http_call_back

    def test_create_o_auth_token(self):
        """
        Generates a new OAuth token with the specified scopes.
        """
        # Parameters for the API call
        body = None

        # Perform the API call through the SDK function
        self.controller.create_o_auth_token(
            body,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 201

    def test_test_endpointwith_arrays(self):
        """
        This endpoint accepts a complex structure with multiple arrays.
        """
        # Parameters for the API call
        body = None

        # Perform the API call through the SDK function
        self.controller.test_endpointwith_arrays(
            body,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200

