"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)


class Address(object):
    """Implementation of the 'Address' model.

    Attributes:
        street (str): The model property of type str.
        city (str): The model property of type str.
        zip (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "street": "street",
        "city": "city",
        "zip": "zip",
    }

    _optionals = [
        "zip",
    ]

    def __init__(
        self,
        street=None,
        city=None,
        zip=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Address instance."""
        # Initialize members of the class
        self.street = street
        self.city = city
        if zip is not APIHelper.SKIP:
            self.zip = zip

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        street =\
            dictionary.get("street")\
            if dictionary.get("street")\
                else None
        city =\
            dictionary.get("city")\
            if dictionary.get("city")\
                else None
        zip =\
            dictionary.get("zip")\
            if dictionary.get("zip")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(street,
                   city,
                   zip,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.street,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                )) \
                and APIHelper.is_valid_type(
                    value=dictionary.city,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("street"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            )) \
            and APIHelper.is_valid_type(
                value=dictionary.get("city"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _street=self.street
        _city=self.city
        _zip=(
            self.zip
            if hasattr(self, "zip")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"street={_street!r}, "
            f"city={_city!r}, "
            f"zip={_zip!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _street=self.street
        _city=self.city
        _zip=(
            self.zip
            if hasattr(self, "zip")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"street={_street!s}, "
            f"city={_city!s}, "
            f"zip={_zip!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
