"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)
from webhooksandcallbacksapi.models.order_item import (
    OrderItem,
)


class CreateOrderRequest(object):
    """Implementation of the 'CreateOrderRequest' model.

    Attributes:
        customer_id (str): Unique identifier for the customer
        items (List[OrderItem]): The model property of type List[OrderItem].
        callback_url (str): URL to receive callback notifications
        document (binary): Binary file upload
        metadata (Any): Additional order metadata
        attributes (Dict[str, str]): The model property of type Dict[str, str].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "customer_id": "customerId",
        "items": "items",
        "callback_url": "callbackUrl",
        "document": "document",
        "metadata": "metadata",
        "attributes": "attributes",
    }

    _optionals = [
        "document",
        "metadata",
        "attributes",
    ]

    def __init__(
        self,
        customer_id=None,
        items=None,
        callback_url=None,
        document=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        attributes=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a CreateOrderRequest instance."""
        # Initialize members of the class
        self.customer_id = customer_id
        self.items = items
        self.callback_url = callback_url
        if document is not APIHelper.SKIP:
            self.document = document
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if attributes is not APIHelper.SKIP:
            self.attributes = attributes

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        customer_id =\
            dictionary.get("customerId")\
            if dictionary.get("customerId")\
                else None
        items = None
        if dictionary.get("items") is not None:
            items = [
                OrderItem.from_dictionary(x)
                    for x in dictionary.get("items")
            ]
        callback_url =\
            dictionary.get("callbackUrl")\
            if dictionary.get("callbackUrl")\
                else None
        document =\
            dictionary.get("document")\
            if dictionary.get("document")\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        attributes =\
            dictionary.get("attributes")\
            if dictionary.get("attributes")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(customer_id,
                   items,
                   callback_url,
                   document,
                   metadata,
                   attributes,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _customer_id=self.customer_id
        _items=self.items
        _callback_url=self.callback_url
        _document=(
            self.document
            if hasattr(self, "document")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _attributes=(
            self.attributes
            if hasattr(self, "attributes")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"customer_id={_customer_id!r}, "
            f"items={_items!r}, "
            f"callback_url={_callback_url!r}, "
            f"document={_document!r}, "
            f"metadata={_metadata!r}, "
            f"attributes={_attributes!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _customer_id=self.customer_id
        _items=self.items
        _callback_url=self.callback_url
        _document=(
            self.document
            if hasattr(self, "document")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _attributes=(
            self.attributes
            if hasattr(self, "attributes")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"customer_id={_customer_id!s}, "
            f"items={_items!s}, "
            f"callback_url={_callback_url!s}, "
            f"document={_document!s}, "
            f"metadata={_metadata!s}, "
            f"attributes={_attributes!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
