"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)


class DeliveryDetails(object):
    """Implementation of the 'DeliveryDetails' model.

    Attributes:
        method (str): The model property of type str.
        eta (datetime): The model property of type datetime.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "method": "method",
        "eta": "eta",
    }

    _optionals = [
        "method",
        "eta",
    ]

    def __init__(
        self,
        method=APIHelper.SKIP,
        eta=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a DeliveryDetails instance."""
        # Initialize members of the class
        if method is not APIHelper.SKIP:
            self.method = method
        if eta is not APIHelper.SKIP:
            self.eta =\
                 APIHelper.apply_datetime_converter(
                eta, APIHelper.RFC3339DateTime)\
                 if eta else None

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        method =\
            dictionary.get("method")\
            if dictionary.get("method")\
                else APIHelper.SKIP
        eta = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("eta")).datetime\
            if dictionary.get("eta") else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(method,
                   eta,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _method=(
            self.method
            if hasattr(self, "method")
            else None
        )
        _eta=(
            self.eta
            if hasattr(self, "eta")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"method={_method!r}, "
            f"eta={_eta!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _method=(
            self.method
            if hasattr(self, "method")
            else None
        )
        _eta=(
            self.eta
            if hasattr(self, "eta")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"method={_method!s}, "
            f"eta={_eta!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
