"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)
from webhooksandcallbacksapi.models.address import (
    Address,
)
from webhooksandcallbacksapi.models.fulfillment_status import (
    FulfillmentStatus,
)
from webhooksandcallbacksapi.models.package import (
    Package,
)


class FulfillmentCallback(object):
    """Implementation of the 'FulfillmentCallback' model.

    Attributes:
        order_id (str): The model property of type str.
        fulfillment_status (FulfillmentStatus): The model property of type
            FulfillmentStatus.
        tracking_number (str): The model property of type str.
        carrier (str): The model property of type str.
        scopes (List[OauthScopeOauthACG]): List of scopes that apply to the OAuth
            token
        estimated_delivery (date): The model property of type date.
        timestamp (datetime): The model property of type datetime.
        document (binary): Binary file upload
        total_weight (float): The model property of type float.
        price (float): The model property of type float.
        quantity (int): The model property of type int.
        long_id (int): The model property of type int.
        fragile (bool): The model property of type bool.
        notes (str): Explicitly nullable field
        items (List[str]): The model property of type List[str].
        packages (List[Package]): The model property of type List[Package].
        address (Address): The model property of type Address.
        metadata (Any): The model property of type Any.
        attributes (Dict[str, str]): The model property of type Dict[str, str].
        delivery_details (str | DeliveryDetails | None): The model property of type
            str | DeliveryDetails | None.
        order_idd (str): The model property of type str.
        fulfillment_statuss (FulfillmentStatuss): The model property of type
            FulfillmentStatuss.
        tracking_numberr (str): The model property of type str.
        carrierr (str): The model property of type str.
        scopess (List[OauthScopeOauthACG]): List of scopes that apply to the OAuth
            token
        estimated_deliveryy (date): The model property of type date.
        timestampp (datetime): The model property of type datetime.
        documentt (binary): Binary file upload
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "order_id": "orderId",
        "fulfillment_status": "fulfillmentStatus",
        "tracking_number": "trackingNumber",
        "carrier": "carrier",
        "scopes": "scopes",
        "estimated_delivery": "estimatedDelivery",
        "timestamp": "timestamp",
        "document": "document",
        "total_weight": "totalWeight",
        "price": "price",
        "quantity": "quantity",
        "long_id": "longId",
        "fragile": "fragile",
        "notes": "notes",
        "items": "items",
        "packages": "packages",
        "address": "address",
        "metadata": "metadata",
        "attributes": "attributes",
        "delivery_details": "deliveryDetails",
        "order_idd": "orderIdd",
        "fulfillment_statuss": "fulfillmentStatuss",
        "tracking_numberr": "trackingNumberr",
        "carrierr": "carrierr",
        "scopess": "scopess",
        "estimated_deliveryy": "estimatedDeliveryy",
        "timestampp": "timestampp",
        "documentt": "documentt",
    }

    _optionals = [
        "tracking_number",
        "carrier",
        "scopes",
        "estimated_delivery",
        "timestamp",
        "document",
        "total_weight",
        "price",
        "quantity",
        "long_id",
        "fragile",
        "notes",
        "items",
        "packages",
        "address",
        "metadata",
        "attributes",
        "delivery_details",
        "order_idd",
        "fulfillment_statuss",
        "tracking_numberr",
        "carrierr",
        "scopess",
        "estimated_deliveryy",
        "timestampp",
        "documentt",
    ]

    _nullables = [
        "order_id",
        "tracking_number",
        "scopes",
        "notes",
        "order_idd",
        "tracking_numberr",
        "scopess",
    ]

    def __init__(
        self,
        order_id=None,
        fulfillment_status=None,
        tracking_number=APIHelper.SKIP,
        carrier=APIHelper.SKIP,
        scopes=APIHelper.SKIP,
        estimated_delivery=APIHelper.SKIP,
        timestamp=APIHelper.SKIP,
        document=APIHelper.SKIP,
        total_weight=APIHelper.SKIP,
        price=APIHelper.SKIP,
        quantity=APIHelper.SKIP,
        long_id=APIHelper.SKIP,
        fragile=APIHelper.SKIP,
        notes=APIHelper.SKIP,
        items=APIHelper.SKIP,
        packages=APIHelper.SKIP,
        address=APIHelper.SKIP,
        metadata=APIHelper.SKIP,
        attributes=APIHelper.SKIP,
        delivery_details=APIHelper.SKIP,
        order_idd=APIHelper.SKIP,
        fulfillment_statuss=APIHelper.SKIP,
        tracking_numberr=APIHelper.SKIP,
        carrierr=APIHelper.SKIP,
        scopess=APIHelper.SKIP,
        estimated_deliveryy=APIHelper.SKIP,
        timestampp=APIHelper.SKIP,
        documentt=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a FulfillmentCallback instance."""
        # Initialize members of the class
        self.order_id = order_id
        self.fulfillment_status = fulfillment_status
        if tracking_number is not APIHelper.SKIP:
            self.tracking_number = tracking_number
        if carrier is not APIHelper.SKIP:
            self.carrier = carrier
        if scopes is not APIHelper.SKIP:
            self.scopes = scopes
        if estimated_delivery is not APIHelper.SKIP:
            self.estimated_delivery = estimated_delivery
        if timestamp is not APIHelper.SKIP:
            self.timestamp =\
                 APIHelper.apply_datetime_converter(
                timestamp, APIHelper.RFC3339DateTime)\
                 if timestamp else None
        if document is not APIHelper.SKIP:
            self.document = document
        if total_weight is not APIHelper.SKIP:
            self.total_weight = total_weight
        if price is not APIHelper.SKIP:
            self.price = price
        if quantity is not APIHelper.SKIP:
            self.quantity = quantity
        if long_id is not APIHelper.SKIP:
            self.long_id = long_id
        if fragile is not APIHelper.SKIP:
            self.fragile = fragile
        if notes is not APIHelper.SKIP:
            self.notes = notes
        if items is not APIHelper.SKIP:
            self.items = items
        if packages is not APIHelper.SKIP:
            self.packages = packages
        if address is not APIHelper.SKIP:
            self.address = address
        if metadata is not APIHelper.SKIP:
            self.metadata = metadata
        if attributes is not APIHelper.SKIP:
            self.attributes = attributes
        if delivery_details is not APIHelper.SKIP:
            self.delivery_details = delivery_details
        if order_idd is not APIHelper.SKIP:
            self.order_idd = order_idd
        if fulfillment_statuss is not APIHelper.SKIP:
            self.fulfillment_statuss = fulfillment_statuss
        if tracking_numberr is not APIHelper.SKIP:
            self.tracking_numberr = tracking_numberr
        if carrierr is not APIHelper.SKIP:
            self.carrierr = carrierr
        if scopess is not APIHelper.SKIP:
            self.scopess = scopess
        if estimated_deliveryy is not APIHelper.SKIP:
            self.estimated_deliveryy = estimated_deliveryy
        if timestampp is not APIHelper.SKIP:
            self.timestampp =\
                 APIHelper.apply_datetime_converter(
                timestampp, APIHelper.RFC3339DateTime)\
                 if timestampp else None
        if documentt is not APIHelper.SKIP:
            self.documentt = documentt

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from webhooksandcallbacksapi.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        order_id =\
            dictionary.get("orderId")\
            if dictionary.get("orderId")\
                else None
        fulfillment_status =\
            dictionary.get("fulfillmentStatus")\
            if dictionary.get("fulfillmentStatus")\
                else None
        tracking_number =\
            dictionary.get("trackingNumber")\
            if "trackingNumber" in dictionary.keys()\
                else APIHelper.SKIP
        carrier =\
            dictionary.get("carrier")\
            if dictionary.get("carrier")\
                else APIHelper.SKIP
        scopes =\
            dictionary.get("scopes")\
            if "scopes" in dictionary.keys()\
                else APIHelper.SKIP
        estimated_delivery = dateutil.parser.parse(
            dictionary.get("estimatedDelivery")).date()\
            if dictionary.get("estimatedDelivery") else APIHelper.SKIP
        timestamp = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("timestamp")).datetime\
            if dictionary.get("timestamp") else APIHelper.SKIP
        document =\
            dictionary.get("document")\
            if dictionary.get("document")\
                else APIHelper.SKIP
        total_weight =\
            dictionary.get("totalWeight")\
            if dictionary.get("totalWeight")\
                else APIHelper.SKIP
        price =\
            dictionary.get("price")\
            if dictionary.get("price")\
                else APIHelper.SKIP
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity")\
                else APIHelper.SKIP
        long_id =\
            dictionary.get("longId")\
            if dictionary.get("longId")\
                else APIHelper.SKIP
        fragile =\
            dictionary.get("fragile")\
            if "fragile" in dictionary.keys()\
                else APIHelper.SKIP
        notes =\
            dictionary.get("notes")\
            if "notes" in dictionary.keys()\
                else APIHelper.SKIP
        items =\
            dictionary.get("items")\
            if dictionary.get("items")\
                else APIHelper.SKIP
        packages = None
        if dictionary.get("packages") is not None:
            packages = [
                Package.from_dictionary(x)
                    for x in dictionary.get("packages")
            ]
        else:
            packages = APIHelper.SKIP
        address =\
            Address.from_dictionary(
                dictionary.get("address"))\
                if "address" in dictionary.keys()\
                else APIHelper.SKIP
        metadata =\
            dictionary.get("metadata")\
            if dictionary.get("metadata")\
                else APIHelper.SKIP
        attributes =\
            dictionary.get("attributes")\
            if dictionary.get("attributes")\
                else APIHelper.SKIP
        delivery_details = APIHelper.deserialize_union_type(
            UnionTypeLookUp.get("FulfillmentCallbackDeliveryDetails"),
            dictionary.get("deliveryDetails"),
            False)\
            if dictionary.get("deliveryDetails") is not None\
            else APIHelper.SKIP
        order_idd =\
            dictionary.get("orderIdd")\
            if "orderIdd" in dictionary.keys()\
                else APIHelper.SKIP
        fulfillment_statuss =\
            dictionary.get("fulfillmentStatuss")\
            if dictionary.get("fulfillmentStatuss")\
                else APIHelper.SKIP
        tracking_numberr =\
            dictionary.get("trackingNumberr")\
            if "trackingNumberr" in dictionary.keys()\
                else APIHelper.SKIP
        carrierr =\
            dictionary.get("carrierr")\
            if dictionary.get("carrierr")\
                else APIHelper.SKIP
        scopess =\
            dictionary.get("scopess")\
            if "scopess" in dictionary.keys()\
                else APIHelper.SKIP
        estimated_deliveryy = dateutil.parser.parse(
            dictionary.get("estimatedDeliveryy")).date()\
            if dictionary.get("estimatedDeliveryy") else APIHelper.SKIP
        timestampp = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("timestampp")).datetime\
            if dictionary.get("timestampp") else APIHelper.SKIP
        documentt =\
            dictionary.get("documentt")\
            if dictionary.get("documentt")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(order_id,
                   fulfillment_status,
                   tracking_number,
                   carrier,
                   scopes,
                   estimated_delivery,
                   timestamp,
                   document,
                   total_weight,
                   price,
                   quantity,
                   long_id,
                   fragile,
                   notes,
                   items,
                   packages,
                   address,
                   metadata,
                   attributes,
                   delivery_details,
                   order_idd,
                   fulfillment_statuss,
                   tracking_numberr,
                   carrierr,
                   scopess,
                   estimated_deliveryy,
                   timestampp,
                   documentt,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.order_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ),
                    is_value_nullable=True) \
                and APIHelper.is_valid_type(
                    value=dictionary.fulfillment_status,
                    type_callable=lambda value:
                        FulfillmentStatus.validate(value))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("orderId"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ),
                is_value_nullable=True) \
            and APIHelper.is_valid_type(
                value=dictionary.get("fulfillmentStatus"),
                type_callable=lambda value:
                    FulfillmentStatus.validate(value))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _order_id=self.order_id
        _fulfillment_status=self.fulfillment_status
        _tracking_number=(
            self.tracking_number
            if hasattr(self, "tracking_number")
            else None
        )
        _carrier=(
            self.carrier
            if hasattr(self, "carrier")
            else None
        )
        _scopes=(
            self.scopes
            if hasattr(self, "scopes")
            else None
        )
        _estimated_delivery=(
            self.estimated_delivery
            if hasattr(self, "estimated_delivery")
            else None
        )
        _timestamp=(
            self.timestamp
            if hasattr(self, "timestamp")
            else None
        )
        _document=(
            self.document
            if hasattr(self, "document")
            else None
        )
        _total_weight=(
            self.total_weight
            if hasattr(self, "total_weight")
            else None
        )
        _price=(
            self.price
            if hasattr(self, "price")
            else None
        )
        _quantity=(
            self.quantity
            if hasattr(self, "quantity")
            else None
        )
        _long_id=(
            self.long_id
            if hasattr(self, "long_id")
            else None
        )
        _fragile=(
            self.fragile
            if hasattr(self, "fragile")
            else None
        )
        _notes=(
            self.notes
            if hasattr(self, "notes")
            else None
        )
        _items=(
            self.items
            if hasattr(self, "items")
            else None
        )
        _packages=(
            self.packages
            if hasattr(self, "packages")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _attributes=(
            self.attributes
            if hasattr(self, "attributes")
            else None
        )
        _delivery_details=(
            self.delivery_details
            if hasattr(self, "delivery_details")
            else None
        )
        _order_idd=(
            self.order_idd
            if hasattr(self, "order_idd")
            else None
        )
        _fulfillment_statuss=(
            self.fulfillment_statuss
            if hasattr(self, "fulfillment_statuss")
            else None
        )
        _tracking_numberr=(
            self.tracking_numberr
            if hasattr(self, "tracking_numberr")
            else None
        )
        _carrierr=(
            self.carrierr
            if hasattr(self, "carrierr")
            else None
        )
        _scopess=(
            self.scopess
            if hasattr(self, "scopess")
            else None
        )
        _estimated_deliveryy=(
            self.estimated_deliveryy
            if hasattr(self, "estimated_deliveryy")
            else None
        )
        _timestampp=(
            self.timestampp
            if hasattr(self, "timestampp")
            else None
        )
        _documentt=(
            self.documentt
            if hasattr(self, "documentt")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"order_id={_order_id!r}, "
            f"fulfillment_status={_fulfillment_status!r}, "
            f"tracking_number={_tracking_number!r}, "
            f"carrier={_carrier!r}, "
            f"scopes={_scopes!r}, "
            f"estimated_delivery={_estimated_delivery!r}, "
            f"timestamp={_timestamp!r}, "
            f"document={_document!r}, "
            f"total_weight={_total_weight!r}, "
            f"price={_price!r}, "
            f"quantity={_quantity!r}, "
            f"long_id={_long_id!r}, "
            f"fragile={_fragile!r}, "
            f"notes={_notes!r}, "
            f"items={_items!r}, "
            f"packages={_packages!r}, "
            f"address={_address!r}, "
            f"metadata={_metadata!r}, "
            f"attributes={_attributes!r}, "
            f"delivery_details={_delivery_details!r}, "
            f"order_idd={_order_idd!r}, "
            f"fulfillment_statuss={_fulfillment_statuss!r}, "
            f"tracking_numberr={_tracking_numberr!r}, "
            f"carrierr={_carrierr!r}, "
            f"scopess={_scopess!r}, "
            f"estimated_deliveryy={_estimated_deliveryy!r}, "
            f"timestampp={_timestampp!r}, "
            f"documentt={_documentt!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _order_id=self.order_id
        _fulfillment_status=self.fulfillment_status
        _tracking_number=(
            self.tracking_number
            if hasattr(self, "tracking_number")
            else None
        )
        _carrier=(
            self.carrier
            if hasattr(self, "carrier")
            else None
        )
        _scopes=(
            self.scopes
            if hasattr(self, "scopes")
            else None
        )
        _estimated_delivery=(
            self.estimated_delivery
            if hasattr(self, "estimated_delivery")
            else None
        )
        _timestamp=(
            self.timestamp
            if hasattr(self, "timestamp")
            else None
        )
        _document=(
            self.document
            if hasattr(self, "document")
            else None
        )
        _total_weight=(
            self.total_weight
            if hasattr(self, "total_weight")
            else None
        )
        _price=(
            self.price
            if hasattr(self, "price")
            else None
        )
        _quantity=(
            self.quantity
            if hasattr(self, "quantity")
            else None
        )
        _long_id=(
            self.long_id
            if hasattr(self, "long_id")
            else None
        )
        _fragile=(
            self.fragile
            if hasattr(self, "fragile")
            else None
        )
        _notes=(
            self.notes
            if hasattr(self, "notes")
            else None
        )
        _items=(
            self.items
            if hasattr(self, "items")
            else None
        )
        _packages=(
            self.packages
            if hasattr(self, "packages")
            else None
        )
        _address=(
            self.address
            if hasattr(self, "address")
            else None
        )
        _metadata=(
            self.metadata
            if hasattr(self, "metadata")
            else None
        )
        _attributes=(
            self.attributes
            if hasattr(self, "attributes")
            else None
        )
        _delivery_details=(
            self.delivery_details
            if hasattr(self, "delivery_details")
            else None
        )
        _order_idd=(
            self.order_idd
            if hasattr(self, "order_idd")
            else None
        )
        _fulfillment_statuss=(
            self.fulfillment_statuss
            if hasattr(self, "fulfillment_statuss")
            else None
        )
        _tracking_numberr=(
            self.tracking_numberr
            if hasattr(self, "tracking_numberr")
            else None
        )
        _carrierr=(
            self.carrierr
            if hasattr(self, "carrierr")
            else None
        )
        _scopess=(
            self.scopess
            if hasattr(self, "scopess")
            else None
        )
        _estimated_deliveryy=(
            self.estimated_deliveryy
            if hasattr(self, "estimated_deliveryy")
            else None
        )
        _timestampp=(
            self.timestampp
            if hasattr(self, "timestampp")
            else None
        )
        _documentt=(
            self.documentt
            if hasattr(self, "documentt")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"order_id={_order_id!s}, "
            f"fulfillment_status={_fulfillment_status!s}, "
            f"tracking_number={_tracking_number!s}, "
            f"carrier={_carrier!s}, "
            f"scopes={_scopes!s}, "
            f"estimated_delivery={_estimated_delivery!s}, "
            f"timestamp={_timestamp!s}, "
            f"document={_document!s}, "
            f"total_weight={_total_weight!s}, "
            f"price={_price!s}, "
            f"quantity={_quantity!s}, "
            f"long_id={_long_id!s}, "
            f"fragile={_fragile!s}, "
            f"notes={_notes!s}, "
            f"items={_items!s}, "
            f"packages={_packages!s}, "
            f"address={_address!s}, "
            f"metadata={_metadata!s}, "
            f"attributes={_attributes!s}, "
            f"delivery_details={_delivery_details!s}, "
            f"order_idd={_order_idd!s}, "
            f"fulfillment_statuss={_fulfillment_statuss!s}, "
            f"tracking_numberr={_tracking_numberr!s}, "
            f"carrierr={_carrierr!s}, "
            f"scopess={_scopess!s}, "
            f"estimated_deliveryy={_estimated_deliveryy!s}, "
            f"timestampp={_timestampp!s}, "
            f"documentt={_documentt!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
