"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)


class InventoryStockIncreaseEvent(object):
    """Implementation of the 'InventoryStockIncreaseEvent' model.

    Attributes:
        inventory_stock_increase_event_type (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "inventory_stock_increase_event_type": "inventoryStockIncreaseEventType",
    }

    def __init__(
        self,
        additional_properties=None):
        """Initialize a InventoryStockIncreaseEvent instance."""
        # Initialize members of the class
        self.inventory_stock_increase_event_type = "stock.increase"

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.inventory_stock_increase_event_type,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        str,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("inventoryStockIncreaseEventType"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    str,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _inventory_stock_increase_event_type=self.inventory_stock_increase_event_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"inventory_stock_increase_event_type={_inventory_stock_increase_event_type!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _inventory_stock_increase_event_type=self.inventory_stock_increase_event_type
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"inventory_stock_increase_event_type={_inventory_stock_increase_event_type!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
