"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)


class OrderItem(object):
    """Implementation of the 'OrderItem' model.

    Attributes:
        product_id (str): The model property of type str.
        quantity (int): The model property of type int.
        price (float): The model property of type float.
        description (str): The model property of type str.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "product_id": "productId",
        "quantity": "quantity",
        "price": "price",
        "description": "description",
    }

    _optionals = [
        "description",
    ]

    def __init__(
        self,
        product_id=None,
        quantity=None,
        price=None,
        description=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a OrderItem instance."""
        # Initialize members of the class
        self.product_id = product_id
        self.quantity = quantity
        self.price = price
        if description is not APIHelper.SKIP:
            self.description = description

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        product_id =\
            dictionary.get("productId")\
            if dictionary.get("productId")\
                else None
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity")\
                else None
        price =\
            dictionary.get("price")\
            if dictionary.get("price")\
                else None
        description =\
            dictionary.get("description")\
            if dictionary.get("description")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(product_id,
                   quantity,
                   price,
                   description,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _product_id=self.product_id
        _quantity=self.quantity
        _price=self.price
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"product_id={_product_id!r}, "
            f"quantity={_quantity!r}, "
            f"price={_price!r}, "
            f"description={_description!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _product_id=self.product_id
        _quantity=self.quantity
        _price=self.price
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"product_id={_product_id!s}, "
            f"quantity={_quantity!s}, "
            f"price={_price!s}, "
            f"description={_description!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
