"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)


class OrderUpdatedEvent(object):
    """Implementation of the 'OrderUpdatedEvent' model.

    Attributes:
        event_type (EventType): The model property of type EventType.
        order_updated_id (int): The model property of type int.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "order_updated_id": "orderUpdatedId",
        "event_type": "eventType",
    }

    _optionals = [
        "event_type",
    ]

    def __init__(
        self,
        order_updated_id=None,
        event_type=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a OrderUpdatedEvent instance."""
        # Initialize members of the class
        if event_type is not APIHelper.SKIP:
            self.event_type = event_type
        self.order_updated_id = order_updated_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        order_updated_id =\
            dictionary.get("orderUpdatedId")\
            if dictionary.get("orderUpdatedId")\
                else None
        event_type =\
            dictionary.get("eventType")\
            if dictionary.get("eventType")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(order_updated_id,
                   event_type,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                    value=dictionary.order_updated_id,
                    type_callable=lambda value:
                        isinstance(
                        value,
                        int,
                ))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
                value=dictionary.get("orderUpdatedId"),
                type_callable=lambda value:
                    isinstance(
                    value,
                    int,
            ))

    def __repr__(self):
        """Return a unambiguous string representation."""
        _event_type=(
            self.event_type
            if hasattr(self, "event_type")
            else None
        )
        _order_updated_id=self.order_updated_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"event_type={_event_type!r}, "
            f"order_updated_id={_order_updated_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _event_type=(
            self.event_type
            if hasattr(self, "event_type")
            else None
        )
        _order_updated_id=self.order_updated_id
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"event_type={_event_type!s}, "
            f"order_updated_id={_order_updated_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
