"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)


class Package(object):
    """Implementation of the 'Package' model.

    Attributes:
        package_id (str): The model property of type str.
        weight (float): The model property of type float.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "package_id": "packageId",
        "weight": "weight",
    }

    _optionals = [
        "package_id",
        "weight",
    ]

    def __init__(
        self,
        package_id=APIHelper.SKIP,
        weight=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Package instance."""
        # Initialize members of the class
        if package_id is not APIHelper.SKIP:
            self.package_id = package_id
        if weight is not APIHelper.SKIP:
            self.weight = weight

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        package_id =\
            dictionary.get("packageId")\
            if dictionary.get("packageId")\
                else APIHelper.SKIP
        weight =\
            dictionary.get("weight")\
            if dictionary.get("weight")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(package_id,
                   weight,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        _package_id=(
            self.package_id
            if hasattr(self, "package_id")
            else None
        )
        _weight=(
            self.weight
            if hasattr(self, "weight")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"package_id={_package_id!r}, "
            f"weight={_weight!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _package_id=(
            self.package_id
            if hasattr(self, "package_id")
            else None
        )
        _weight=(
            self.weight
            if hasattr(self, "weight")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"package_id={_package_id!s}, "
            f"weight={_weight!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
