"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)


class SmsNotificationCallback(object):
    """Implementation of the 'SmsNotificationCallback' model.

    Attributes:
        message_id (str): The model property of type str.
        phone_number (str): The model property of type str.
        status (Status2): The model property of type Status2.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "message_id": "messageId",
        "phone_number": "phoneNumber",
        "status": "status",
    }

    _optionals = [
        "message_id",
        "phone_number",
        "status",
    ]

    def __init__(
        self,
        message_id=APIHelper.SKIP,
        phone_number=APIHelper.SKIP,
        status=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a SmsNotificationCallback instance."""
        # Initialize members of the class
        if message_id is not APIHelper.SKIP:
            self.message_id = message_id
        if phone_number is not APIHelper.SKIP:
            self.phone_number = phone_number
        if status is not APIHelper.SKIP:
            self.status = status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        message_id =\
            dictionary.get("messageId")\
            if dictionary.get("messageId")\
                else APIHelper.SKIP
        phone_number =\
            dictionary.get("phoneNumber")\
            if dictionary.get("phoneNumber")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(message_id,
                   phone_number,
                   status,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _message_id=(
            self.message_id
            if hasattr(self, "message_id")
            else None
        )
        _phone_number=(
            self.phone_number
            if hasattr(self, "phone_number")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"message_id={_message_id!r}, "
            f"phone_number={_phone_number!r}, "
            f"status={_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _message_id=(
            self.message_id
            if hasattr(self, "message_id")
            else None
        )
        _phone_number=(
            self.phone_number
            if hasattr(self, "phone_number")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"message_id={_message_id!s}, "
            f"phone_number={_phone_number!s}, "
            f"status={_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
