"""webhooksandcallbacksapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)


class WebhookUpdate(object):
    """Implementation of the 'WebhookUpdate' model.

    Attributes:
        url (str): The model property of type str.
        events (List[str]): The model property of type List[str].
        secret (str): The model property of type str.
        active (bool): The model property of type bool.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "url": "url",
        "events": "events",
        "secret": "secret",
        "active": "active",
    }

    _optionals = [
        "url",
        "events",
        "secret",
        "active",
    ]

    def __init__(
        self,
        url=APIHelper.SKIP,
        events=APIHelper.SKIP,
        secret=APIHelper.SKIP,
        active=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a WebhookUpdate instance."""
        # Initialize members of the class
        if url is not APIHelper.SKIP:
            self.url = url
        if events is not APIHelper.SKIP:
            self.events = events
        if secret is not APIHelper.SKIP:
            self.secret = secret
        if active is not APIHelper.SKIP:
            self.active = active

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        url =\
            dictionary.get("url")\
            if dictionary.get("url")\
                else APIHelper.SKIP
        events =\
            dictionary.get("events")\
            if dictionary.get("events")\
                else APIHelper.SKIP
        secret =\
            dictionary.get("secret")\
            if dictionary.get("secret")\
                else APIHelper.SKIP
        active =\
            dictionary.get("active")\
            if "active" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(url,
                   events,
                   secret,
                   active,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _events=(
            self.events
            if hasattr(self, "events")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _active=(
            self.active
            if hasattr(self, "active")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!r}, "
            f"events={_events!r}, "
            f"secret={_secret!r}, "
            f"active={_active!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _url=(
            self.url
            if hasattr(self, "url")
            else None
        )
        _events=(
            self.events
            if hasattr(self, "events")
            else None
        )
        _secret=(
            self.secret
            if hasattr(self, "secret")
            else None
        )
        _active=(
            self.active
            if hasattr(self, "active")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"url={_url!s}, "
            f"events={_events!s}, "
            f"secret={_secret!s}, "
            f"active={_active!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
