"""swaggerpetstoreopenapi30.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.authentication.multiple.or_auth_group import (
    Or,
)
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from swaggerpetstoreopenapi30.api_helper import (
    APIHelper,
)
from swaggerpetstoreopenapi30.apis.base_api import (
    BaseApi,
)
from swaggerpetstoreopenapi30.configuration import (
    Server,
)
from swaggerpetstoreopenapi30.exceptions.api_exception import (
    ApiException,
)
from swaggerpetstoreopenapi30.http.http_method_enum import (
    HttpMethodEnum,
)
from swaggerpetstoreopenapi30.models.api_response import (
    ApiResponse,
)
from swaggerpetstoreopenapi30.models.pet import (
    Pet,
)


class PetApi(BaseApi):
    """A Controller to access Endpoints in the swaggerpetstoreopenapi30 API."""

    def __init__(self, config):
        """Initialize PetApi object."""
        super(PetApi, self).__init__(config)

    def update_pet(self,
                   name,
                   photo_urls,
                   id=None,
                   category=None,
                   tags=None,
                   status=None):
        """Perform a PUT request to /pet.

        Update an existing pet by Id.

        Args:
            name (str): The request form parameter.
            photo_urls (List[str]): The request form parameter.
            id (int, optional): The request form parameter.
            category (Category, optional): The request form parameter.
            tags (List[Tag], optional): The request form parameter.
            status (PetStatus, optional): pet status in the store

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/pet")
            .http_method(HttpMethodEnum.PUT)
            .form_param(Parameter()
                .key("name")
                .value(name)
                .is_required(True))
            .form_param(Parameter()
                .key("photoUrls")
                .value(photo_urls)
                .is_required(True))
            .form_param(Parameter()
                .key("id")
                .value(id))
            .form_param(Parameter()
                .key("category")
                .value(category))
            .form_param(Parameter()
                .key("tags")
                .value(tags))
            .form_param(Parameter()
                .key("status")
                .value(status))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("petstore_auth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(Pet.from_dictionary)
            .is_api_response(True)
            .local_error("400", "Invalid ID supplied", ApiException)
            .local_error("404", "Pet not found", ApiException)
            .local_error("422", "Validation exception", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def add_pet(self,
                name,
                photo_urls,
                id=None,
                category=None,
                tags=None,
                status=None):
        """Perform a POST request to /pet.

        Add a new pet to the store.

        Args:
            name (str): The request form parameter.
            photo_urls (List[str]): The request form parameter.
            id (int, optional): The request form parameter.
            category (Category, optional): The request form parameter.
            tags (List[Tag], optional): The request form parameter.
            status (PetStatus, optional): pet status in the store

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/pet")
            .http_method(HttpMethodEnum.POST)
            .form_param(Parameter()
                .key("name")
                .value(name)
                .is_required(True))
            .form_param(Parameter()
                .key("photoUrls")
                .value(photo_urls)
                .is_required(True))
            .form_param(Parameter()
                .key("id")
                .value(id))
            .form_param(Parameter()
                .key("category")
                .value(category))
            .form_param(Parameter()
                .key("tags")
                .value(tags))
            .form_param(Parameter()
                .key("status")
                .value(status))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("petstore_auth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(Pet.from_dictionary)
            .is_api_response(True)
            .local_error("400", "Invalid input", ApiException)
            .local_error("422", "Validation exception", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def find_pets_by_status(self,
                            status=None):
        """Perform a GET request to /pet/findByStatus.

        Multiple status values can be provided with comma separated strings.

        Args:
            status (PetStatus, optional): Status values that need to be considered
                for filter

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/pet/findByStatus")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("status")
                .value(status))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("petstore_auth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(Pet.from_dictionary)
            .is_api_response(True)
            .local_error("400", "Invalid status value", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def find_pets_by_tags(self,
                          tags=None):
        """Perform a GET request to /pet/findByTags.

        Multiple tags can be provided with comma separated strings. Use tag1, tag2,
        tag3 for testing.

        Args:
            tags (List[str], optional): Tags to filter by

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/pet/findByTags")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("tags")
                .value(tags))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("petstore_auth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(Pet.from_dictionary)
            .is_api_response(True)
            .local_error("400", "Invalid tag value", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def get_pet_by_id(self,
                      pet_id):
        """Perform a GET request to /pet/{petId}.

        Returns a single pet.

        Args:
            pet_id (int): ID of pet to return

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/pet/{petId}")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("petId")
                .value(pet_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Or(Single("api_key"), Single("petstore_auth"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(Pet.from_dictionary)
            .is_api_response(True)
            .local_error("400", "Invalid ID supplied", ApiException)
            .local_error("404", "Pet not found", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def update_pet_with_form(self,
                             pet_id,
                             name=None,
                             status=None):
        """Perform a POST request to /pet/{petId}.

        Updates a pet resource based on the form data.

        Args:
            pet_id (int): ID of pet that needs to be updated
            name (str, optional): Name of pet that needs to be updated
            status (str, optional): Status of pet that needs to be updated

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/pet/{petId}")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("petId")
                .value(pet_id)
                .is_required(True)
                .should_encode(True))
            .query_param(Parameter()
                .key("name")
                .value(name))
            .query_param(Parameter()
                .key("status")
                .value(status))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("petstore_auth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(Pet.from_dictionary)
            .is_api_response(True)
            .local_error("400", "Invalid input", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def delete_pet(self,
                   pet_id,
                   api_key=None):
        """Perform a DELETE request to /pet/{petId}.

        Delete a pet.

        Args:
            pet_id (int): Pet id to delete
            api_key (str, optional): The request header parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Pet deleted

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/pet/{petId}")
            .http_method(HttpMethodEnum.DELETE)
            .template_param(Parameter()
                .key("petId")
                .value(pet_id)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("api_key")
                .value(api_key))
            .auth(Single("petstore_auth")),
        ).response(
            ResponseHandler()
            .is_api_response(True)
            .local_error("400", "Invalid pet value", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def upload_file(self,
                    pet_id,
                    additional_metadata=None,
                    body=None):
        """Perform a POST request to /pet/{petId}/uploadImage.

        Upload image of the pet.

        Args:
            pet_id (int): ID of pet to update
            additional_metadata (str, optional): Additional Metadata
            body (typing.BinaryIO, optional): The request form parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/pet/{petId}/uploadImage")
            .http_method(HttpMethodEnum.POST)
            .template_param(Parameter()
                .key("petId")
                .value(pet_id)
                .is_required(True)
                .should_encode(True))
            .query_param(Parameter()
                .key("additionalMetadata")
                .value(additional_metadata))
            .multipart_param(Parameter()
                .key("body")
                .value(body)
                .default_content_type("application/octet-stream"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .auth(Single("petstore_auth")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ApiResponse.from_dictionary)
            .is_api_response(True)
            .local_error("400", "No file uploaded", ApiException)
            .local_error("404", "Pet not found", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()
