"""swaggerpetstoreopenapi30.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: D410, E501, E101, D206
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from swaggerpetstoreopenapi30.api_helper import (
    APIHelper,
)
from swaggerpetstoreopenapi30.apis.base_api import (
    BaseApi,
)
from swaggerpetstoreopenapi30.configuration import (
    Server,
)
from swaggerpetstoreopenapi30.exceptions.api_exception import (
    ApiException,
)
from swaggerpetstoreopenapi30.http.http_method_enum import (
    HttpMethodEnum,
)
from swaggerpetstoreopenapi30.models.user import (
    User,
)
from swaggerpetstoreopenapi30.utilities.xml_utilities import (
    XmlUtilities,
)


class UserApi(BaseApi):
    """A Controller to access Endpoints in the swaggerpetstoreopenapi30 API."""

    def __init__(self, config):
        """Initialize UserApi object."""
        super(UserApi, self).__init__(config)

    def create_user(self,
                    id=None,
                    username=None,
                    first_name=None,
                    last_name=None,
                    email=None,
                    password=None,
                    phone=None,
                    user_status=None):
        """Perform a POST request to /user.

        This can only be done by the logged in user.

        Args:
            id (int, optional): The request form parameter.
            username (str, optional): The request form parameter.
            first_name (str, optional): The request form parameter.
            last_name (str, optional): The request form parameter.
            email (str, optional): The request form parameter.
            password (str, optional): The request form parameter.
            phone (str, optional): The request form parameter.
            user_status (int, optional): User Status

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/user")
            .http_method(HttpMethodEnum.POST)
            .form_param(Parameter()
                .key("id")
                .value(id))
            .form_param(Parameter()
                .key("username")
                .value(username))
            .form_param(Parameter()
                .key("firstName")
                .value(first_name))
            .form_param(Parameter()
                .key("lastName")
                .value(last_name))
            .form_param(Parameter()
                .key("email")
                .value(email))
            .form_param(Parameter()
                .key("password")
                .value(password))
            .form_param(Parameter()
                .key("phone")
                .value(phone))
            .form_param(Parameter()
                .key("userStatus")
                .value(user_status))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded"))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(User.from_dictionary)
            .is_api_response(True)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def create_users_with_list_input(self,
                                     body=None):
        """Perform a POST request to /user/createWithList.

        Creates list of users with given input array.

        Args:
            body (List[User], optional): The request body parameter.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. Successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/user/createWithList")
            .http_method(HttpMethodEnum.POST)
            .header_param(Parameter()
                .key("Content-Type")
                .value("application/json"))
            .body_param(Parameter()
                .value(body))
            .header_param(Parameter()
                .key("accept")
                .value("application/json"))
            .body_serializer(APIHelper.json_serialize),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(User.from_dictionary)
            .is_api_response(True)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def login_user(self,
                   username=None,
                   password=None):
        """Perform a GET request to /user/login.

        Log into the system.

        Args:
            username (str, optional): The user name for login
            password (str, optional): The password for login in clear text

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/user/login")
            .http_method(HttpMethodEnum.GET)
            .query_param(Parameter()
                .key("username")
                .value(username))
            .query_param(Parameter()
                .key("password")
                .value(password))
            .header_param(Parameter()
                .key("accept")
                .value("application/xml")),
        ).response(
            ResponseHandler()
            .deserializer(XmlUtilities.deserialize_xml)
            .is_xml_response(True)
            .is_api_response(True)
            .local_error("400", "Invalid username/password supplied", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def logout_user(self):
        """Perform a GET request to /user/logout.

        Log user out of the system.

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/user/logout")
            .http_method(HttpMethodEnum.GET),
        ).response(
            ResponseHandler()
            .is_api_response(True)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def get_user_by_name(self,
                         usersname):
        """Perform a GET request to /user/{usersname}.

        Get user detail based on username.

        Args:
            usersname (str): The username that needs to be processed

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/user/{usersname}")
            .http_method(HttpMethodEnum.GET)
            .template_param(Parameter()
                .key("usersname")
                .value(usersname)
                .is_required(True)
                .should_encode(True))
            .header_param(Parameter()
                .key("accept")
                .value("application/json")),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(User.from_dictionary)
            .is_api_response(True)
            .local_error("400", "Invalid username supplied", ApiException)
            .local_error("404", "User not found", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def update_user(self,
                    usersname,
                    id=None,
                    username=None,
                    first_name=None,
                    last_name=None,
                    email=None,
                    password=None,
                    phone=None,
                    user_status=None):
        """Perform a PUT request to /user/{usersname}.

        This can only be done by the logged in user.

        Args:
            usersname (str): The username that needs to be processed
            id (int, optional): The request form parameter.
            username (str, optional): The request form parameter.
            first_name (str, optional): The request form parameter.
            last_name (str, optional): The request form parameter.
            email (str, optional): The request form parameter.
            password (str, optional): The request form parameter.
            phone (str, optional): The request form parameter.
            user_status (int, optional): User Status

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. successful operation

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/user/{usersname}")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                .key("usersname")
                .value(usersname)
                .is_required(True)
                .should_encode(True))
            .form_param(Parameter()
                .key("id")
                .value(id))
            .form_param(Parameter()
                .key("username")
                .value(username))
            .form_param(Parameter()
                .key("firstName")
                .value(first_name))
            .form_param(Parameter()
                .key("lastName")
                .value(last_name))
            .form_param(Parameter()
                .key("email")
                .value(email))
            .form_param(Parameter()
                .key("password")
                .value(password))
            .form_param(Parameter()
                .key("phone")
                .value(phone))
            .form_param(Parameter()
                .key("userStatus")
                .value(user_status))
            .header_param(Parameter()
                            .key("content-type")
                            .value("application/x-www-form-urlencoded")),
        ).response(
            ResponseHandler()
            .is_api_response(True)
            .local_error("400", "bad request", ApiException)
            .local_error("404", "user not found", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()

    def delete_user(self,
                    usersname):
        """Perform a DELETE request to /user/{usersname}.

        This can only be done by the logged in user.

        Args:
            usersname (str): The username that needs to be processed

        Returns:
            ApiResponse: An object with the response value as well as other useful
                information such as status codes and headers. User deleted

        Raises:
            ApiException: When an error occurs while fetching the data from the
                remote API. This exception includes the HTTP Response code, an error
                message, and the HTTP body that was received in the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/user/{usersname}")
            .http_method(HttpMethodEnum.DELETE)
            .template_param(Parameter()
                .key("usersname")
                .value(usersname)
                .is_required(True)
                .should_encode(True)),
        ).response(
            ResponseHandler()
            .is_api_response(True)
            .local_error("400", "Invalid username supplied", ApiException)
            .local_error("404", "User not found", ApiException)
            .local_error("default", "Unexpected error", ApiException),
        ).execute()
