"""swaggerpetstoreopenapi30.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from swaggerpetstoreopenapi30.apis.base_api import (
    BaseApi,
)
from swaggerpetstoreopenapi30.apis.pet_api import (
    PetApi,
)
from swaggerpetstoreopenapi30.apis.store_api import (
    StoreApi,
)
from swaggerpetstoreopenapi30.apis.user_api import (
    UserApi,
)
from swaggerpetstoreopenapi30.configuration import (
    Configuration,
    Environment,
)
from swaggerpetstoreopenapi30.http.auth.api_key import (
    ApiKey,
)
from swaggerpetstoreopenapi30.http.auth.petstore_auth import (
    PetstoreAuth,
)


class Swaggerpetstoreopenapi30Client(object):
    """Client that provide access to the Swaggerpetstoreopenapi30Client APIs."""

    @LazyProperty
    def pet(self):
        """Provide access to the PetApi endpoints."""
        return PetApi(self.global_configuration)

    @LazyProperty
    def store(self):
        """Provide access to the StoreApi endpoints."""
        return StoreApi(self.global_configuration)

    @LazyProperty
    def user(self):
        """Provide access to the UserApi endpoints."""
        return UserApi(self.global_configuration)

    @property
    def petstore_auth(self):
        """Provide access to the PetstoreAuth auth manager."""
        return self.auth_managers["petstore_auth"]

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=30, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 logging_configuration=None, environment=Environment.PRODUCTION,
                 petstore_auth_credentials=None, api_key_credentials=None,
                 config=None):
        """Initialize a new instance of Swaggerpetstoreopenapi30Client."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings,
            logging_configuration=logging_configuration,
            environment=environment,
            petstore_auth_credentials=petstore_auth_credentials,
            api_key_credentials=api_key_credentials)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseApi.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseApi.user_agent(),
                BaseApi.user_agent_parameters())

        self.auth_managers = {
            "petstore_auth": PetstoreAuth(self.config.petstore_auth_credentials,
                                          self.global_configuration),
            "api_key": ApiKey(self.config.api_key_credentials),
        }
        self.global_configuration =\
            self.global_configuration.auth_managers(self.auth_managers)

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            Swaggerpetstoreopenapi30Client instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
