"""
 webhooksandcallbacksapi

 This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""
from __future__ import annotations

from typing import (
    List,
    Union,
)

from webhooksandcallbacksapi.api_helper import (
    APIHelper,
)
from webhooksandcallbacksapi.events.unknown_event import (
    UnknownEvent,
)
from webhooksandcallbacksapi.http.request import (
    Request,
)
from webhooksandcallbacksapi.models.audit_log_event import (
    AuditLogEvent,
)
from webhooksandcallbacksapi.models.root_level_primitive_one_of_event_request import (
    RootLevelPrimitiveOneOfEventRequest,
)
from webhooksandcallbacksapi.models.root_level_primitive_one_of_event_request_1 import (
    RootLevelPrimitiveOneOfEventRequest1,
)
from webhooksandcallbacksapi.utilities.union_type_lookup import (
    UnionTypeLookUp,
)

WebhooksNoVerificationEventType = Union[
    AuditLogEvent,
    RootLevelPrimitiveOneOfEventRequest,
    int,
    List[RootLevelPrimitiveOneOfEventRequest1],
    List[int],
    UnknownEvent,
]

class WebhooksNoVerificationHandler:
    """
     Demo group with no payload verification (unsigned webhooks).
    """

    @staticmethod
    def parse_event(request: Request) -> WebhooksNoVerificationEventType:
        """
         Parse the event.

        :return: AuditLogEvent, RootLevelPrimitiveOneOfEventRequest, int,
                 List[RootLevelPrimitiveOneOfEventRequest1], List[int] for successful
                 parsing; UnknownEvent for unknown events.
        :rtype: Union[AuditLogEvent, RootLevelPrimitiveOneOfEventRequest, int,
                List[RootLevelPrimitiveOneOfEventRequest1], List[int], UnknownEvent]
        """
        # Deserialize payload
        try:
            union = UnionTypeLookUp.get("webhooksNoVerification")
            return APIHelper.deserialize_union_type(union, request.raw_body)
        except Exception as e:
            return UnknownEvent([
                "Deserialization failed.",
                str(e),
            ])
